name: iOS Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Kodu Cek
      uses: actions/checkout@v4

    - name: Java Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Xcode Ayarla
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Calistirma İznini Ver
      run: chmod +x gradlew

    - name: KMP iOS Framework Derle
      run: ./gradlew :shared:embedAndSignAppleFrameworkForXcode

    - name: Xcode ile Uygulamayi Derle
      run: |
        xcodebuild -project iosApp/iosApp.xcodeproj \
                   -scheme iosApp \
                   -sdk iphoneos \
                   -configuration Release \
                   CODE_SIGNING_ALLOWED=NO \
                   BUILD_DIR=build

    - name: Ciktiyi Yukle
      uses: actions/upload-artifact@v4
      with:
        name: ios-uygulama-çıktısı
        path: iosApp/build/Release-iphoneos/